### ISSUE TITLE
Improve article 2309.07864

### ISSUE THREAD

**Issue by Aike505** [dginev/ar5iv#422] opened 2023-12-29 04:15 UTC
**Exact location of issue**

Article fails to convert due to error cascade with `forest.sty`

DG: Edited description

**Comment by dginev** [comment] 2023-12-29 15:35
Thanks for the report! Checked [the log](https://ar5iv.labs.arxiv.org/log/2309.07864), we are missing `forest.sty` support in latexml.

**Comment by dginev** [comment] 2023-12-29 19:39
But this is also a duplicate of #421 (I had assumed the article was different).

**Closed by dginev** 2023-12-29 19:39 UTC
Labels: bug, medium, needs-latex-package
