### ISSUE TITLE
Improve article 1707.01495

### ISSUE THREAD

**Issue by yuxiliu1995** [dginev/ar5iv#239] opened 2022-10-12 08:45 UTC
**Exact location of issue**
[section 4](https://ar5iv.labs.arxiv.org/html/1707.01495#S4)

**Problem details**

figure 2 is too long. Each subfigure is put on a separate line, making a really long figure.

**expected behavior**

![image](https://user-images.githubusercontent.com/33951560/195295808-a31a75f6-f6e7-46fc-986d-10ade767e505.png)

**Desktop (please complete the following information)**
 - OS: Windows
 - Browser firefox, chrome

**Comment by dginev** [comment] 2022-10-12 12:19
Likely caused by the sizing computation being inaccurate, and similar in nature to issue #163

**Comment by dginev** [comment] 2023-01-18 16:59
This article has now been updated to the latest version, which only includes the PDF via:

```tex
% I included PDF because I couldn't get the paper to compile on arXiv.
\pdfoutput=1
\documentclass{article}
\usepackage[final]{pdfpages}
\begin{document}
\includepdf[pages=1-last]{HER-2018.pdf}
\end{document}
```

Which is a shame. I will close here with wontfix and work the image issues in the articles that are still submitted with sources.

**Closed by dginev** 2023-01-18 16:59 UTC
Labels: bug, medium, figures, fidelity
