### ISSUE TITLE
Improve article 1805.12152

### ISSUE THREAD

**Issue by Mahbodmajid** [dginev/ar5iv#264] opened 2022-10-18 20:01 UTC
**Exact location of issue**
> [1805.12152](https://ar5iv.labs.arxiv.org/html/1805.12152)

**Problem details**
The compiled html belongs to an [older, v1](https://arxiv.org/abs/1805.12152v1) version of the paper.

**Expected behavior**
The compiled html should be the [newer, v5](https://arxiv.org/abs/1805.12152v5) version of the paper.  

**Desktop**
 - OS: macOS
 - Browser: chrome

**Comment by dginev** [comment] 2022-10-18 20:13
Duplicate of #48 . Using the latest article versions is the most requested ar5iv feature, and I am currently working with the arXiv team to find a good long-term solution for the HTML output to stay up to date with the arXiv sources.

**Closed by dginev** 2022-10-18 20:13 UTC
Labels: duplicate
