### ISSUE TITLE
Improve article 1802.01548

### ISSUE THREAD

**Issue by luckywood** [dginev/ar5iv#77] opened 2022-02-16 15:40 UTC
conversion fails, i.e. only the title and abstract gets converted
(for unknown reason)

**Comment by dginev** [comment] 2022-02-16 15:45
Thank you for the report!

The unknown reason can be investigated through the "conversion report" link at the bottom of the page.
It appears this is due to the regression we have with interpreting Latex 3 in texlive 2020, which has a tracking issue at latexml's [#1762](https://github.com/brucemiller/LaTeXML/issues/1762).

We can double-check this article converts better after that regression has been regressed, thanks for adding the example!

**Comment by dginev** [comment] 2022-03-03 14:26
@luckywood the responsible latexml regression has been fixed, feel free to take another look:
[1802.01548](https://ar5iv.labs.arxiv.org/html/1802.01548)

There is one more error left in this article, related to another (smaller) generic latexml regression that leaves an undefined `\KV@enumitem@noitemsep@default` marker in the log.

**Comment by dginev** [comment] 2023-01-18 15:33
The latest state of this article is error-free, and we have resolved the duplicated frontmatter.

I will close the issue for now, thanks for the report @luckywood ! But definitely feel welcome to open new issue when you encounter any of the remaining inaccuracies in ar5iv.

**Closed by dginev** 2023-01-18 15:33 UTC
Labels: bug, medium, fidelity
